name: Build OSCam .deb (ICAM + EMU + HEXDUMP)
on:
push:
branches: [ master ]
workflow_dispatch:
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Repository klonen
uses: actions/checkout@v3
- name: Build-Tools installieren
run: |
sudo apt update
sudo apt install -y build-essential libssl-dev ...
- name: Kompilieren
run: |
make distclean || true
touch config.sh
echo "CONFIGURE_FLAGS='--enable-emu --enable-hexdump'" > config.sh
make CONF_DIR=/etc/tuxbox/config
- name: .deb-Paket erstellen
run: |
...
- name: Export als Artefakt
uses: actions/upload-artifact@v4
with:
name: oscam-icam-deb
path: oscam-deb.deb
