name: Build OSCam ICAM Hex

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev libusb-1.0-0-dev libpcsclite-dev libdvbcsa-dev pkg-config
      - run: |
          cat > config.sh <<EOF
          CONFIG=arm-linux-gnueabihf
          WITH_EMU=1
          WITH_SOFTCAM=1
          WITH_STREAMRELAY=1
          WITH_EXTENDED_CW=1
          WITH_EMMLOG_HEX=1
          USE_LIBUSB=1
          USE_LIBDVBCSA=1
          WITH_SSL=1
          EOF
          make config
          make -j$(nproc)
      - uses: actions/upload-artifact@v3
        with:
          name: oscam-arm-icam-hex
          path: Distribution/oscam
